# ci configuration
stages:
  - install_meteor
  - environment_versions
  - npm_install
  - create_bundle

job_install_meteor:
  stage: install_meteor
  script:
    - curl https://install.meteor.com/ | sh

job_environment_versions:
  stage: environment_versions
  script:
    - PATH=$PATH:$(find $HOME/.meteor/packages -name dev_bundle)/bin
    - node --version
    - npm --version
    - $HOME/.meteor/meteor --version

job_npm_install:
  stage: npm_install
  script:
    - PATH=$PATH:$(find $HOME/.meteor/packages -name dev_bundle)/bin
    - npm install --production

job_create_bundle:
  stage: create_bundle
  script:
    - $HOME/.meteor/meteor build ./.build --server https://ketchup.scytec.de --architecture os.linux.x86_64
  artifacts:
    name: ketchup
    paths:
    - ./.build/*.gz